CloudCemeteryManagementSystem/CloudCemeteryManagementSystem/Models/LotOwner.cs
using System;
using System.ComponentModel.DataAnnotations;
using System.Collections.Generic;

namespace CloudCemeteryManagementSystem.Models
{
        public enum State
    {
        [Display(Name = "Alabama")]
        AL,
        [Display(Name = "Alaska")]
        AK,
        [Display(Name = "Arkansas")]
        AR,
        [Display(Name = "Arizona")]
        AZ,
        [Display(Name = "California")]
        CA,
        [Display(Name = "Colorado")]
        CO,
        [Display(Name = "Connecticut")]
        CT,
        [Display(Name = "Delaware")]
        DE,
        [Display(Name = "Florida")]
        FL,
        [Display(Name = "Georgia")]
        GA,
        [Display(Name = "Hawaii")]
        HI,
        [Display(Name = "Iowa")]
        IA,
        [Display(Name = "Idaho")]
        ID,
        [Display(Name = "Illinois")]
        IL,
        [Display(Name = "Indiana")]
        IN,
        [Display(Name = "Kansas")]
        KS,
        [Display(Name = "Kentucky")]
        KY,
        [Display(Name = "Louisiana")]
        LA,
        [Display(Name = "Massachusetts")]
        MA,
        [Display(Name = "Maryland")]
        MD,
        [Display(Name = "Maine")]
        ME,
        [Display(Name = "Michigan")]
        MI,
        [Display(Name = "Minnesota")]
        MN,
        [Display(Name = "Missouri")]
        MO,
        [Display(Name = "Mississippi")]
        MS,
        [Display(Name = "Montana")]
        MT,
        [Display(Name = "North Carolina")]
        NC,
        [Display(Name = "North Dakota")]
        ND,
        [Display(Name = "Nebraska")]
        NE,
        [Display(Name = "New Hampshire")]
        NH,
        [Display(Name = "New Jersey")]
        NJ,
        [Display(Name = "New Mexico")]
        NM,
        [Display(Name = "Nevada")]
        NV,
        [Display(Name = "New York")]
        NY,
        [Display(Name = "Oklahoma")]
        OK,
        [Display(Name = "Ohio")]
        OH,
        [Display(Name = "Oregon")]
        OR,
        [Display(Name = "Pennsylvania")]
        PA,
        [Display(Name = "Rhode Island")]
        RI,
        [Display(Name = "South Carolina")]
        SC,
        [Display(Name = "South Dakota")]
        SD,
        [Display(Name = "Tennessee")]
        TN,
        [Display(Name = "Texas")]
        TX,
        [Display(Name = "Utah")]
        UT,
        [Display(Name = "Virginia")]
        VA,
        [Display(Name = "Vermont")]
        VT,
        [Display(Name = "Washington")]
        WA,
        [Display(Name = "Wisconsin")]
        WI,
        [Display(Name = "West Virginia")]
        WV,
        [Display(Name = "Wyoming")]
        WY

    }
    public class LotOwner
    {
        public int Id { get; set; }

        [Display(Name = "Lot Owner Number")]
        public int LotOwnerNumber { get; set; }

        [Display(Name = "Lot Number")]
        public string LotNumber { get; set; }
        
        [Required, Display(Name = "First Name")]
        public string FirstName { get; set; }
        
        [Required, Display(Name = "Last Name")]
        public string LastName { get; set; }
        
        public string Address { get; set; }

        public string City { get; set; }

        public State State { get; set; }
        
        [RegularExpression(@"^\d{5}(-\d{4})?$", ErrorMessage = "Invalid Zip")]
        public string Zip { get; set; }
        
        [DataType(DataType.Date), Display(Name = "Date Issued")]
        public DateTime DateIssued { get; set; }
        
        public float Cost { get; set; }
        
        [Display(Name = "Lots Purchased")]
        public int NumberOfLotsPurchased { get; set; }

        public List<Interred> Interreds { get; set; }
        
        [Display(Name = "Last Edited by")]
        public string LastEditedBy { get; set; }

    }
}

CloudCemeteryManagementSystem/CloudCemeteryManagementSystem/Controllers/InterredController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Security.Claims;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.EntityFrameworkCore;
using CloudCemeteryManagementSystem.Data;
using CloudCemeteryManagementSystem.Models;

namespace CloudCemeteryManagementSystem.Controllers
{
    public class InterredController : Controller
    {
        private readonly ApplicationDbContext _context;

        public InterredController(ApplicationDbContext context)
        {
            _context = context;
        }


        public async Task<IActionResult> Index(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var lotOwner =  await _context.LotOwner
                .Where(m => m.Id == id).Include(m => m.Interreds)
                .ToListAsync();

            // if a lotOwner does not exist with the Id it return NotFound
            bool isEmpty = !lotOwner.Any();
            if (isEmpty)
            {
                return NotFound();
            }

            return View(lotOwner);
        }

        // GET: Interred/Details/5
        public async Task<IActionResult> Details(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var interred = await _context.Interred
                .FirstOrDefaultAsync(m => m.Id == id);
            if (interred == null)
            {
                return NotFound();
            }

            return View(interred);
        }

        // GET: Interred/Create/LotOwner/1
        public async Task<IActionResult> Create(int? id)
        {
            var lotOwnerId = id;
            if (lotOwnerId == null)
            {
                return NotFound();
            }

            var lotOwner = await _context.LotOwner.FindAsync(lotOwnerId);
            if (lotOwner == null)
            {
                return NotFound();
            }
            ViewBag.LotOwner = lotOwner;
            return View();
        }

        // POST: Interred/Create
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Create([Bind(
            "LotOwnerId,FirstName,LastName,DateOfDeath,PlaceOfDeath,PropertyStyle,Gender"+
            "DateOfBurial,ApprovalDate,TimeOfMass,MaritalStatus,SectionOfCemetery,"+
            "IsVeteran,NameOfFuneralHome,NameOfSpouse,NameOfChurch,Information")] Interred interred)
        {
            if (ModelState.IsValid)
            {
                interred.LastEditedBy = User.FindFirstValue(ClaimTypes.Name);
                _context.Add(interred);
                await _context.SaveChangesAsync();
                return RedirectToAction(nameof(Index), new{id = interred.LotOwnerId});
            }
            return View(interred);
        }

        // GET: Interred/Edit/5
        public async Task<IActionResult> Edit(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var interred = await _context.Interred.FindAsync(id);
            if (interred == null)
            {
                return NotFound();
            }
            ViewData["LotOwnerId"] = new SelectList(_context.Set<LotOwner>(), "LotOwnerId", "LotOwnerId", interred.LotOwnerId);
            return View(interred);
        }

        // POST: Interred/Edit/5
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Edit(int id, [Bind(
            "Id,LotOwnerId,InternmentNumber,FirstName,LastName,DateOfDeath,PlaceOfDeath,PropertyStyle,Gender"+
            "DateOfBurial,ApprovalDate,TimeOfMass,MaritalStatus,SectionOfCemetery,"+
            "IsVeteran,NameOfFuneralHome,NameOfSpouse,NameOfChurch,Information")] Interred interred)
        {
            if (id != interred.Id)
            {
                return NotFound();
            }

            if (ModelState.IsValid)
            {
                try
                {
                    _context.Update(interred);
                    await _context.SaveChangesAsync();
                }
                catch (DbUpdateConcurrencyException)
                {
                    if (!InterredExists(interred.Id))
                    {
                        return NotFound();
                    }
                    else
                    {
                        throw;
                    }
                }
                return RedirectToAction(nameof(Index), new{id = interred.LotOwnerId});
            }
            ViewData["LotOwnerId"] = new SelectList(_context.Set<LotOwner>(), "LotOwnerId", "LotOwnerId", interred.LotOwnerId);
            return View(interred);
        }

        // GET: Interred/Delete/5
        public async Task<IActionResult> Delete(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var interred = await _context.Interred
                .FirstOrDefaultAsync(m => m.Id == id);
            if (interred == null)
            {
                return NotFound();
            }

            return View(interred);
        }

        // POST: Interred/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> DeleteConfirmed(int id)
        {
            var interred = await _context.Interred.FindAsync(id);
            _context.Interred.Remove(interred);
            await _context.SaveChangesAsync();
            return RedirectToAction(nameof(Index), new{id = interred.LotOwnerId});
        }

        private bool InterredExists(int id)
        {
            return _context.Interred.Any(e => e.Id == id);
        }
    }
}

CloudCemeteryManagementSystem/CloudCemeteryManagementSystem/Controllers/LotOwnerController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Security.Claims;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.EntityFrameworkCore;
using CloudCemeteryManagementSystem.Data;
using CloudCemeteryManagementSystem.Models;

namespace CloudCemeteryManagementSystem.Controllers
{
    public class LotOwnerController : Controller
    {
        private readonly ApplicationDbContext _context;

        public LotOwnerController(ApplicationDbContext context)
        {
            _context = context;
        }

        // GET: LotOwner
        public async Task<IActionResult> Index()
        {
            return View(await _context.LotOwner.ToListAsync());
        }
        

        // GET: LotOwner/Details/5
        public async Task<IActionResult> Details(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var lotOwner = await _context.LotOwner
                .FirstOrDefaultAsync(m => m.Id == id);
            if (lotOwner == null)
            {
                return NotFound();
            }

            return View(lotOwner);
        }

        // GET: LotOwner/Create
        public IActionResult Create()
        {
            return View();
        }

        // POST: LotOwner/Create
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Create([Bind("Id,LotOwnerNumber,LotNumber,FirstName,LastName,Address,City,State,Zip,DateIssued,Cost,NumberOfLotsPurchased")] LotOwner lotOwner)
        {
            if (ModelState.IsValid)
            {
                lotOwner.LastEditedBy = User.FindFirstValue(ClaimTypes.Name);
                _context.Add(lotOwner);
                await _context.SaveChangesAsync();
                return RedirectToAction(nameof(Index));
            }
            return View(lotOwner);
        }

        // GET: LotOwner/Edit/5
        public async Task<IActionResult> Edit(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var lotOwner = await _context.LotOwner.FindAsync(id);
            if (lotOwner == null)
            {
                return NotFound();
            }
            return View(lotOwner);
        }

        // POST: LotOwner/Edit/5
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Edit(int id, [Bind("Id,LotOwnerNumber,LotNumber,FirstName,LastName,Address,City,State,Zip,DateIssued,Cost,NumberOfLotsPurchased")] LotOwner lotOwner)
        {
            if (id != lotOwner.Id)
            {
                return NotFound();
            }

            if (ModelState.IsValid)
            {
                try
                {
                    _context.Update(lotOwner);
                    await _context.SaveChangesAsync();
                }
                catch (DbUpdateConcurrencyException)
                {
                    if (!LotOwnerExists(lotOwner.Id))
                    {
                        return NotFound();
                    }
                    else
                    {
                        throw;
                    }
                }
                return RedirectToAction(nameof(Index));
            }
            return View(lotOwner);
        }

        // GET: LotOwner/Delete/5
        public async Task<IActionResult> Delete(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var lotOwner = await _context.LotOwner
                .FirstOrDefaultAsync(m => m.Id == id);
            if (lotOwner == null)
            {
                return NotFound();
            }

            return View(lotOwner);
        }

        // POST: LotOwner/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> DeleteConfirmed(int id)
        {
            var lotOwner = await _context.LotOwner.FindAsync(id);
            _context.LotOwner.Remove(lotOwner);
            await _context.SaveChangesAsync();
            return RedirectToAction(nameof(Index));
        }

        private bool LotOwnerExists(int id)
        {
            return _context.LotOwner.Any(e => e.Id == id);
        }
    }
}

CloudCemeteryManagementSystem/CloudCemeteryManagementSystem/Views/LotOwner/Create.cshtml
@model CloudCemeteryManagementSystem.Models.LotOwner

@{
    ViewData["Title"] = "Create";
}

<head>
    <link rel="stylesheet" href="~/css/DashBack.css">

    <style type="text/css">
        body {
            background-image: url('https://www.pixeden.com/media/k2/galleries/93/003-subtle-light-pattern-background-texture.jpg');
            background-size: cover;
            background-attachment: fixed;
            margin: 0px;
            padding: 0px;
            font-family: 'Times New Roman';
        }

        .addlotowner {
            color: white;
        }

        .block {
            position: center;
            background-color: black;
            color: white;
            padding-top: 3.5%;
            padding-left: 18.7%;
            padding-right: 18.7%;
            padding-bottom: 100%;
            z-index: 8000;
            opacity: 0.97;
            font-family: "Times New Roman";
        }

        hr {
            display: block;
            margin-before: 0.5em;
            margin-after: 0.5em;
            margin-start: auto;
            margin-end: auto;
            overflow: hidden;
            border-style: inset;
            border-width: 1px;
        }
    </style>
</head>

<div style="color: white;">
    <div class="block">
        <div class="addlotowner">

            <h1 style="color: white; font-family:'Times New Roman';"><b>Create a new Lot Owner</b></h1>
            <hr />

            <div class="row">
                <div class="container">
                    <form asp-action="Create">
                        <div asp-validation-summary="ModelOnly" class="text-danger"></div>
                        <div class="form-group">
                            <label asp-for="LotNumber" class="control-label"></label>
                            <input asp-for="LotNumber" class="form-control" />
                            <span asp-validation-for="LotNumber" class="text-danger"></span>
                        </div>
                        <div class="form-row">
                            <div class="form-group col-md-6">
                                <label asp-for="FirstName" class="control-label"></label>
                                <input asp-for="FirstName" class="form-control" />
                                <span asp-validation-for="FirstName" class="text-danger"></span>
                            </div>
                            <div class="form-group col-md-6">
                                <label asp-for="LastName" class="control-label"></label>
                                <input asp-for="LastName" class="form-control" />
                                <span asp-validation-for="LastName" class="text-danger"></span>
                            </div>
                        </div>
                        <div class="form-group">
                            <label asp-for="Address" class="control-label"></label>
                            <input asp-for="Address" class="form-control" />
                            <span asp-validation-for="Address" class="text-danger"></span>
                        </div>
                        <div class="form-group">
                            <label asp-for="City" class="control-label"></label>
                            <input asp-for="City" class="form-control" />
                            <span asp-validation-for="City" class="text-danger"></span>
                        </div>
                        <div class="form-row">
                            <div class="form-group col-md-6">
                                <label asp-for="State" class="control-label"></label>
                                <select asp-for="State" asp-items="Html.GetEnumSelectList<State>()" class="form-control">
                                    <option selected="selected" value="">Please select</option>
                                </select>
                                <span asp-validation-for="State" class="text-danger"></span>
                            </div>
                            <div class="form-group col-md-6">
                                <label asp-for="Zip" class="control-label"></label>
                                <input asp-for="Zip" class="form-control" />
                                <span asp-validation-for="Zip" class="text-danger"></span>
                            </div>
                        </div>
                        <div class="form-group">
                            <label asp-for="DateIssued" class="control-label"></label>
                            <input asp-for="DateIssued" class="form-control" />
                            <span asp-validation-for="DateIssued" class="text-danger"></span>
                        </div>
                        <div class="form-row">
                            <div class="form-group col-md-6">
                                <label asp-for="NumberOfLotsPurchased" class="control-label"></label>
                                <input asp-for="NumberOfLotsPurchased" class="form-control" />
                                <span asp-validation-for="NumberOfLotsPurchased" class="text-danger"></span>
                            </div>
                            <div class="form-group col-md-6">
                                <label asp-for="Cost" class="control-label"></label>
                                <input asp-for="Cost" class="form-control" />
                                <span asp-validation-for="Cost" class="text-danger"></span>
                            </div>
                        </div>
                        <div class="form-group">
                            <input type="submit" value="Create" class="btn btn-primary" />
                        </div>
                    </form>
                </div>
            </div>

            <div>
                <a asp-action="Index">Back to List</a>
            </div>
        </div>
    </div>
</div>

@section Scripts {
    @{await Html.RenderPartialAsync("_ValidationScriptsPartial");}
}

CloudCemeteryManagementSystem/CloudCemeteryManagementSystem/Views/LotOwner/Index.cshtml
@model IEnumerable<CloudCemeteryManagementSystem.Models.LotOwner>

@{
    ViewData["Title"] = "Index";
}

<head>
    <link rel="stylesheet" href="~/css/DashBack.css">

    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.css" />


    <style type="text/css">
        body {
            background-image: url('https://www.pixeden.com/media/k2/galleries/93/003-subtle-light-pattern-background-texture.jpg');
            background-size: cover;
            background-attachment: fixed;
            margin: 0px;
            padding: 0px;
            font-family: 'Times New Roman';
        }

        .addlotowner {
            color: white;
        }

        a:first-child {
            border-right: none;
        }

        .block {
            position: center;
            background-color: black;
            color: white;
            padding-top: 3.5%;
            padding-left: 18.7%;
            padding-right: 18.7%;
            padding-bottom: 100%;
            z-index: 8000;
            opacity: 0.97;
            font-family: "Times New Roman";
        }

        hr {
            display: block;
            margin-before: 0.5em;
            margin-after: 0.5em;
            margin-start: auto;
            margin-end: auto;
            overflow: hidden;
            border-style: inset;
            border-width: 1px;
        }
    </style>
</head>

<div style="color: white;">
    <div class="block" style="width: 100%;">
        <div class="addlotowner">

            <h1 style="color: white; font-family:'Times New Roman';"><b>Index</b></h1>
            <hr />

            <p>
                <a asp-action="Create">Create New Lot Owner</a>
            </p>
            <div>
                <table class="table table-responsive" id="InfoTable" style="color:white; padding:1px;">
                    <thead>
                        <tr>
                            <th>
                                @Html.DisplayNameFor(model => model.LotOwnerNumber)
                            </th>
                            <th>
                                @Html.DisplayNameFor(model => model.FirstName)
                            </th>
                            <th>
                                @Html.DisplayNameFor(model => model.LastName)
                            </th>
                            <th>
                                @Html.DisplayNameFor(model => model.State)
                            </th>
                            <th>
                                @Html.DisplayNameFor(model => model.NumberOfLotsPurchased)
                            </th>
                            <th></th>
                        </tr>
                    </thead>
                    <tbody style="color:white;">
                        @if (!Model.Any())
                        {
                            <tr style="color:black;"><td text-center colspan="6" style="text-align:center;">No Interreds for this Lot Owner</td></tr>

                        }
                        else
                        {
                            @foreach (var item in Model)
                            {
                                <tr style="color:black;" Title="Last Edited By: @item.LastEditedBy">
                                    <td>
                                        @Html.DisplayFor(modelItem => item.LotOwnerNumber)
                                    </td>
                                    <td>
                                        @Html.DisplayFor(modelItem => item.FirstName)
                                    </td>
                                    <td>
                                        @Html.DisplayFor(modelItem => item.LastName)
                                    </td>
                                    <td>
                                        @Html.DisplayFor(modelItem => item.State)
                                    </td>
                                    <td>
                                        @Html.DisplayFor(modelItem => item.NumberOfLotsPurchased)
                                    </td>
                                    <td>
                                        <a asp-action="Index" asp-controller="Interred" asp-route-id="@item.Id">View</a> |
                                        <a asp-action="Edit" asp-route-id="@item.Id">Edit</a> |
                                        <a asp-action="Details" asp-route-id="@item.Id">Details</a> |
                                        <a asp-action="Delete" asp-route-id="@item.Id">Delete</a>
                                    </td>
                                </tr>
                            }
                        }
                    </tbody>
                    <tfoot style="color:white;">
                        <tr>
                            <th>
                                @Html.DisplayNameFor(model => model.LotOwnerNumber)
                            </th>
                            <th>
                                @Html.DisplayNameFor(model => model.FirstName)
                            </th>
                            <th>
                                @Html.DisplayNameFor(model => model.LastName)
                            </th>
                            <th>
                                @Html.DisplayNameFor(model => model.State)
                            </th>
                            <th>
                                @Html.DisplayNameFor(model => model.NumberOfLotsPurchased)
                            </th>
                            <th></th>
                        </tr>
                    </tfoot>
                </table>
            </div>
        </div>
    </div>
</div>