CloudCemeteryManagementSystem/CloudCemeteryManagementSystem/Controllers/RoleController.cs
using System;
using System.Collections.Generic;
using System.ComponentModel;
using System.ComponentModel.DataAnnotations;
using System.Linq;
using System.Threading.Tasks;
using CloudCemeteryManagementSystem.Areas.Identity;
using CloudCemeteryManagementSystem.Models;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Identity;
using Microsoft.AspNetCore.Mvc;

namespace CloudCemeteryManagementSystem.Controllers
{
    //[Authorize(Roles = "Administrator")]
    public class RoleController : Controller
    {
        private RoleManager<IdentityRole> roleManager;
        private UserManager<ApplicationUser> userManager;

        public RoleController(RoleManager<IdentityRole> roleMgr, UserManager<ApplicationUser> userMgr)
        {
            roleManager = roleMgr;
            userManager = userMgr;
        }

        public ViewResult Index() => View(roleManager.Roles);

        public IActionResult Create() => View();

        public async Task<IActionResult> Update(string id)
        {
            IdentityRole role = await roleManager.FindByIdAsync(id);
            List<ApplicationUser> members = new List<ApplicationUser>();
            List<ApplicationUser> nonMembers = new List<ApplicationUser>();

            foreach (ApplicationUser user in userManager.Users )
            {
                var list = await userManager.IsInRoleAsync(user, role.Name) ? members : nonMembers;
                list.Add(user);
            }

            return View(new RoleEdit
            {
                Role = role,
                Members = members,
                NonMembers = nonMembers
            });

        }

        [HttpPost]
        public async Task<IActionResult> Update(RoleModification model)
        {
            IdentityResult result;
            if (ModelState.IsValid)
            {
                foreach (string userId in model.AddIds ?? new string[] { })
                {
                    ApplicationUser user = await userManager.FindByIdAsync(userId);
                    if (user != null)
                    {
                        result = await userManager.AddToRoleAsync(user, model.RoleName);
                        if (!result.Succeeded)
                            Errors(result);
                    }
                }
            }

            if (ModelState.IsValid)
                return RedirectToAction(nameof(Index));
            else
                return await Update(model.RoleId);
        }

        [HttpPost]
        public async Task<IActionResult> Create([Required] string name)
        {
            if (ModelState.IsValid)
            {
                IdentityResult result = await roleManager.CreateAsync(new IdentityRole(name));
                if (result.Succeeded)
                    return RedirectToAction("Index");
                else
                {
                    Errors(result);
                }
            }

            return View(name);
        }

        [HttpPost]
        public async Task<IActionResult> Delete(string id)
        {
            IdentityRole role = await roleManager.FindByIdAsync(id);
            if (role != null)
            {
                IdentityResult result = await roleManager.DeleteAsync(role);
                if (result.Succeeded)
                {
                    return RedirectToAction("Index");
                }
                else
                {
                    Errors(result);
                }
            }
            else
            {
                ModelState.AddModelError("", "No role found");
            }

            return View("Index", roleManager.Roles);
        }

        private void Errors(IdentityResult result)
        {
            foreach (IdentityError error in result.Errors)
                ModelState.AddModelError("", error.Description);
        }

    }
}

CloudCemeteryManagementSystem/CloudCemeteryManagementSystem/Controllers/UserManagementController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Security.Policy;
using System.Threading.Tasks;
using CloudCemeteryManagementSystem.Data;
using CloudCemeteryManagementSystem.Areas.Identity.Pages.Account;
using CloudCemeteryManagementSystem.Models;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Identity;
using Microsoft.AspNetCore.Identity.EntityFrameworkCore;
using Microsoft.AspNetCore.Mvc;
using Microsoft.EntityFrameworkCore;
using CloudCemeteryManagementSystem.Areas.Identity;

namespace CloudCemeteryManagementSystem.Controllers
{
    public class UserManagementController : Controller
    {
        private static UserManager<ApplicationUser> userManager;
        private List<RegisterModel.InputModel> Input = new List<RegisterModel.InputModel>();

        public UserManagementController(RoleManager<IdentityRole> roleMgr, UserManager<ApplicationUser> userMgr)
        {
            userManager = userMgr;
        }
        
        [HttpPost]
        public async Task<IActionResult> Delete(string Id)
        {
            ApplicationUser user = await userManager.FindByIdAsync(Id);
            if (user != null)
            {
                IdentityResult result = await userManager.DeleteAsync(user);
                if (result.Succeeded)
                {
                    return RedirectToAction("Index");
                }
                else
                {
                    Errors(result);
                }
            }
            else
            {
                ModelState.AddModelError("", "No role found");
            }

            return View("Index", new UserManagementModel
            {
                userRoleList = Input,
                users = userManager.Users
            });
        }

        //[Authorize(Roles = "Administrator")]
        public async Task<IActionResult> Index()
        {

            var users = await userManager.Users.ToListAsync();
            RegisterModel.InputModel inputModel = new RegisterModel.InputModel();

            foreach (var v in users)
            {
                inputModel = new RegisterModel.InputModel();
                var roles = await userManager.GetRolesAsync(v);
                inputModel.Email = v.UserName;
                inputModel.FirstName = v.FirstName;
                inputModel.LastName = v.LastName;
                inputModel.role = "No Role";
                inputModel.RegisteredBy = v.RegisteredBy;
                inputModel.Id = v.Id;
                foreach (var r in roles)
                {
                    if (!inputModel.role.Contains(","))
                    {
                        inputModel.role = r;
                    }
                    else
                    {
                        inputModel.role = "," + r;
                    }
                }
                Input.Add(inputModel);
            }
            return View("Index",new UserManagementModel
            {
               userRoleList = Input
            });
        }

        private void Errors(IdentityResult result)
        {
            foreach (IdentityError error in result.Errors)
                ModelState.AddModelError("", error.Description);
        }
    }


}

CloudCemeteryManagementSystem/CloudCemeteryManagementSystem/Views/UserManagement/Index.cshtml
@{
    ViewData["Title"] = "Index";
}

@model UserManagementModel
@using Microsoft.AspNetCore.Identity

<style type="text/css">
    body {
        background-image: url('https://www.pixeden.com/media/k2/galleries/93/003-subtle-light-pattern-background-texture.jpg');
        background-size: cover;
        background-attachment: fixed;
        margin: 0px;
        padding: 0px;
        font-family: 'Times New Roman';
    }
</style>

<head>

    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <meta name="description" content="">
    <meta name="author" content="">

    <title>Dashboard</title>

    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.css" />

</head>
<style>
    .text-block {
        border: 2px solid black;
        border-radius: 25px;
        bottom: -416px;
        right: 530px;
        background-color: white;
        color: white;
        margin-top: 20px;
        padding-top: 25px;
        padding-left: 50px;
        padding-right: 50px;
        padding-bottom: 50px;
        opacity: 0.7;
    }


    .block {
        position: center;
        background-color: black;
        color: white;
        padding-top: 3.5%;
        padding-left: 18.7%;
        padding-right: 18.7%;
        padding-bottom: 100%;
        z-index: 8000;
        opacity: 0.97;
        font-family: "Times New Roman";
    }

    hr {
        display: block;
        margin-before: 0.5em;
        margin-after: 0.5em;
        margin-start: auto;
        margin-end: auto;
        overflow: hidden;
        border-style: inset;
        border-width: 1px;
    }
</style>

<div style="color: white;">
    <div class="block" style="position: center; color: white;">
        <div>
            <h1 style="color: white; font-family:'Times New Roman';"><b>Users</b></h1>
            <hr />

            <div class="form-group" style="">
                <span>
                    <a asp-area="Identity" asp-page="/Account/Register" class="btn btn-dark">Add a User</a>
                </span>
                <span>
                    <a asp-controller="Role" asp-action="Index" class="btn btn-dark">Modify Roles</a>
                </span>
            </div>


            <table class="table table-sm table-bordered table-bordered table-responsive" style="color: white; position: relative;">
                <tr><th>Last Name</th><th>First Name</th><th>Email</th><th>Role</th><th>Delete</th></tr>
                @foreach (var user in Model.userRoleList)
                {
                    <tr title="Registered by: @user.RegisteredBy">

                        <td>@user.FirstName</td>
                        <td>@user.LastName</td>
                        <td>@user.Email</td>
                        <td>@user.role</td>
                        <td>
                            <form asp-action="Delete" asp-route-id="@user.Id" method="post">
                                <button type="submit" class="btn btn-sm btn-danger">
                                    Delete
                                </button>
                            </form>

                    </tr>
                }
            </table>
        </div>
    </div>
</div>