CloudCemeteryManagementSystem/CloudCemeteryManagementSystem/Controllers/HomeController.cs
using System;
using System.Collections.Generic;
using System.Diagnostics;
using System.Linq;
using System.Text.RegularExpressions;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.Extensions.Logging;
using CloudCemeteryManagementSystem.Models;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Identity.EntityFrameworkCore;
using Newtonsoft.Json;

namespace CloudCemeteryManagementSystem.Controllers
{
    public class HomeController : Controller
    {
        private readonly ILogger<HomeController> _logger;

        public HomeController()//ILogger<HomeController> logger)
        {
            //_logger = logger;
        }

        public IActionResult Index()
        {
            return View();
        }

        public IActionResult Privacy()
        {
            return View();
        }

        public IActionResult SearchLotOwnerInfo()
        {
            ViewData["Message"] = "Your Dashboard.";

            return View();
        }

        public IActionResult SearchInterredInfo()
        {
            ViewData["Message"] = "Your Dashboard.";

            return View();
        }

        public IActionResult Map()
        {
            ViewData["Message"] = "Your Dashboard.";

            return View();
        }

        [HttpPost]
        public ActionResult StoreMarkers(string latlng)
        {
            int start = latlng.IndexOf("(");
            int end = latlng.IndexOf(")");
            int length = end - start;
            string parsedString = latlng.Substring(start + 1, length - 1);
            
            
            
            return View("Map");
        }

        public IActionResult AdminSettings()
        {
            ViewData["Message"] = "Your Dashboard.";

            return View();
        }

        public IActionResult WorkerSettings()
        {
            ViewData["Message"] = "Your Dashboard.";

            return View();
        }
        

        [ResponseCache(Duration = 0, Location = ResponseCacheLocation.None, NoStore = true)]
        public IActionResult Error()
        {
            return View(new ErrorViewModel {RequestId = Activity.Current?.Id ?? HttpContext.TraceIdentifier});
        }

        public IActionResult Dashboard()
        {
            if (User.IsInRole("Administrator"))
            {
                return View("AdminDashboard");
            }

            if (User.IsInRole("Worker"))
            {
                return View("WorkerDashboardPlaceHolder");
            }

            return View("ErrorPleaseSignIn");
        }
    }
}

CloudCemeteryManagementSystem/CloudCemeteryManagementSystem/Controllers/LotOwnerController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Security.Claims;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.EntityFrameworkCore;
using CloudCemeteryManagementSystem.Data;
using CloudCemeteryManagementSystem.Models;

namespace CloudCemeteryManagementSystem.Controllers
{
    public class LotOwnerController : Controller
    {
        private readonly ApplicationDbContext _context;

        public LotOwnerController(ApplicationDbContext context)
        {
            _context = context;
        }

        // GET: LotOwner
        public async Task<IActionResult> Index()
        {
            return View(await _context.LotOwner.ToListAsync());
        }
        

        // GET: LotOwner/Details/5
        public async Task<IActionResult> Details(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var lotOwner = await _context.LotOwner
                .FirstOrDefaultAsync(m => m.Id == id);
            if (lotOwner == null)
            {
                return NotFound();
            }

            return View(lotOwner);
        }

        // GET: LotOwner/Create
        public IActionResult Create()
        {
            return View();
        }

        // POST: LotOwner/Create
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Create([Bind("Id,LotOwnerNumber,LotNumber,FirstName,LastName,Address,City,State,Zip,DateIssued,Cost,NumberOfLotsPurchased")] LotOwner lotOwner)
        {
            if (ModelState.IsValid)
            {
                lotOwner.LastEditedBy = User.FindFirstValue(ClaimTypes.Name);
                _context.Add(lotOwner);
                await _context.SaveChangesAsync();
                return RedirectToAction(nameof(Index));
            }
            return View(lotOwner);
        }

        // GET: LotOwner/Edit/5
        public async Task<IActionResult> Edit(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var lotOwner = await _context.LotOwner.FindAsync(id);
            if (lotOwner == null)
            {
                return NotFound();
            }
            return View(lotOwner);
        }

        // POST: LotOwner/Edit/5
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Edit(int id, [Bind("Id,LotOwnerNumber,LotNumber,FirstName,LastName,Address,City,State,Zip,DateIssued,Cost,NumberOfLotsPurchased")] LotOwner lotOwner)
        {
            if (id != lotOwner.Id)
            {
                return NotFound();
            }

            if (ModelState.IsValid)
            {
                try
                {
                    _context.Update(lotOwner);
                    await _context.SaveChangesAsync();
                }
                catch (DbUpdateConcurrencyException)
                {
                    if (!LotOwnerExists(lotOwner.Id))
                    {
                        return NotFound();
                    }
                    else
                    {
                        throw;
                    }
                }
                return RedirectToAction(nameof(Index));
            }
            return View(lotOwner);
        }

        // GET: LotOwner/Delete/5
        public async Task<IActionResult> Delete(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var lotOwner = await _context.LotOwner
                .FirstOrDefaultAsync(m => m.Id == id);
            if (lotOwner == null)
            {
                return NotFound();
            }

            return View(lotOwner);
        }

        // POST: LotOwner/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> DeleteConfirmed(int id)
        {
            var lotOwner = await _context.LotOwner.FindAsync(id);
            _context.LotOwner.Remove(lotOwner);
            await _context.SaveChangesAsync();
            return RedirectToAction(nameof(Index));
        }

        private bool LotOwnerExists(int id)
        {
            return _context.LotOwner.Any(e => e.Id == id);
        }
    }
}

CloudCemeteryManagementSystem/CloudCemeteryManagementSystem/Controllers/UserManagementController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Security.Policy;
using System.Threading.Tasks;
using CloudCemeteryManagementSystem.Data;
using CloudCemeteryManagementSystem.Areas.Identity.Pages.Account;
using CloudCemeteryManagementSystem.Models;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Identity;
using Microsoft.AspNetCore.Identity.EntityFrameworkCore;
using Microsoft.AspNetCore.Mvc;
using Microsoft.EntityFrameworkCore;
using CloudCemeteryManagementSystem.Areas.Identity;

namespace CloudCemeteryManagementSystem.Controllers
{
    public class UserManagementController : Controller
    {
        private static UserManager<ApplicationUser> userManager;
        private List<RegisterModel.InputModel> Input = new List<RegisterModel.InputModel>();

        public UserManagementController(RoleManager<IdentityRole> roleMgr, UserManager<ApplicationUser> userMgr)
        {
            userManager = userMgr;
        }
        
        [HttpPost]
        public async Task<IActionResult> Delete(string Id)
        {
            ApplicationUser user = await userManager.FindByIdAsync(Id);
            if (user != null)
            {
                IdentityResult result = await userManager.DeleteAsync(user);
                if (result.Succeeded)
                {
                    return RedirectToAction("Index");
                }
                else
                {
                    Errors(result);
                }
            }
            else
            {
                ModelState.AddModelError("", "No role found");
            }

            return View("Index", new UserManagementModel
            {
                userRoleList = Input,
                users = userManager.Users
            });
        }

        //[Authorize(Roles = "Administrator")]
        public async Task<IActionResult> Index()
        {

            var users = await userManager.Users.ToListAsync();
            RegisterModel.InputModel inputModel = new RegisterModel.InputModel();

            foreach (var v in users)
            {
                inputModel = new RegisterModel.InputModel();
                var roles = await userManager.GetRolesAsync(v);
                inputModel.Email = v.UserName;
                inputModel.FirstName = v.FirstName;
                inputModel.LastName = v.LastName;
                inputModel.role = "No Role";
                inputModel.RegisteredBy = v.RegisteredBy;
                inputModel.Id = v.Id;
                foreach (var r in roles)
                {
                    if (!inputModel.role.Contains(","))
                    {
                        inputModel.role = r;
                    }
                    else
                    {
                        inputModel.role = "," + r;
                    }
                }
                Input.Add(inputModel);
            }
            return View("Index",new UserManagementModel
            {
               userRoleList = Input
            });
        }

        private void Errors(IdentityResult result)
        {
            foreach (IdentityError error in result.Errors)
                ModelState.AddModelError("", error.Description);
        }
    }


}

CloudCemeteryManagementSystem/CloudCemeteryManagementSystem/Views/Home/AdminDashboard.cshtml
@{
    ViewBag.Title = "Dashboard";
}

<head>

    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <meta name="description" content="">
    <meta name="author" content="">

    <title>Dashboard</title>

    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.css" />
    @*<link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/4.4.1/css/bootstrap.min.css">*@
    <link rel="stylesheet" href="~/css/DashBack.css" />
    <link href="https://fonts.googleapis.com/css?family=Open+Sans:300i,400" rel="stylesheet">

</head>
<style type="text/css">
    body {
        background-image: url(https://i.pinimg.com/originals/6d/a3/c4/6da3c4228b17b9357ce6c3bd42a4c665.jpg);
        background-size: cover;
        background-attachment: fixed;
        margin: 0px;
        padding: 0px;
        font-family: 'Times New Roman';
    }
</style>

<!-- Page Content -->

<div class="con">

    <div class="card">
        <a asp-area="" asp-controller="LotOwner" asp-action="Index" class="stretched-link"></a>
        <h3 class="title">Add Lot</h3>
        <div class="bar">
            <div class="emptybar"></div>
            <div class="filledbar"></div>
        </div>

        <div class="circle">
            <img src="https://cdn0.iconfinder.com/data/icons/funeral-basic-lineal/512/39_Credit_Card-512.png" alt="..." style="position:center; width:80%; height:80%;" />

        </div>
    </div>
    @*
    <div class="card">
        <a asp-area="" asp-controller="Home" asp-action="SearchLotOwnerInfo" class="stretched-link"></a>
        <h3 class="title">Search Lot</h3>
        <div class="bar">
            <div class="emptybar"></div>
            <div class="filledbar"></div>
        </div>

        <div class="circle">
            <img src="https://cdn1.iconfinder.com/data/icons/cloud-computing-51/66/19-512.png" alt="..." style="position:center; width:80%; height:80%;" />

        </div>
    </div>
        *@
    <div class="card">
        <a asp-area="" asp-controller="Home" asp-action="Map" class="stretched-link"></a>
        <h3 class="title">Map</h3>
        <div class="bar">
            <div class="emptybar"></div>
            <div class="filledbar"></div>
        </div>

        <div class="circle">
            <img src="https://cdn2.iconfinder.com/data/icons/cosmo-mobile/40/map_1-512.png" alt="..." style="position:center; width:80%; height:80%;" />

        </div>
    </div>

    <div class="card">
        <a asp-area="" asp-controller="UserManagement" asp-action="Index" class="stretched-link"></a>
        <h3 class="title">Settings</h3>
        <div class="bar">
            <div class="emptybar"></div>
            <div class="filledbar"></div>
        </div>

        <div class="circle">
            <img src="https://cdn0.iconfinder.com/data/icons/business-and-finance-glyph-24/64/business-and-finance-glyph-24-12-512.png" alt="..." style="position:center; width:80%; height:80%;" />

        </div>
    </div>

</div>



@*<div>
        <span style="opacity:0;">This sentence is invisible ____________________________________________________________________________________________________________</span>
        <div class="text-block">
        <div class="cards">
            <div class="row row-cols-1 row-cols-md-3">
                <div class="col mb-4">
                    <div class="card">
                        <img src="https://cdn1.iconfinder.com/data/icons/cloud-computing-51/66/19-512.png" class="card-img-top" alt="..." />
                        <div class="card-body">
                            <h5 class="card-title">Search Lot Owner Info</h5>
                            <p class="card-text">Search for specific lot owner information.</p>
                            <a asp-area="" asp-controller="Home" asp-action="SearchLotOwnerInfo" class="stretched-link"></a>
                        </div>
                    </div>
                </div>
                <div class="col mb-4">
                    <div class="card">
                        <img src="https://cdn0.iconfinder.com/data/icons/funeral-basic-lineal/512/39_Credit_Card-512.png" class="card-img-top" alt="..." />
                        <div class="card-body">
                            <h5 class="card-title">Add Lot Owner</h5>
                            <p class="card-text">
                                Add Lot Owner information. <span style="opacity:0;">This sentence is invisible</span>
                            </p>
                            <a asp-area="" asp-controller="LotOwner" asp-action="Index" class="stretched-link"></a>
                        </div>
                    </div>
                </div>
                <div class="col mb-4">
                    <div class="card">
                        <img src="https://cdn2.iconfinder.com/data/icons/cosmo-mobile/40/map_1-512.png" class="card-img-top" alt="..." />
                        <div class="card-body">
                            <h5 class="card-title">Map</h5>
                            <p class="card-text">
                                View a map of the Cemetery. <span style="opacity:0;">This sentence is invisible</span>
                            </p>
                            <a asp-area="" asp-controller="Home" asp-action="Map" class="stretched-link"></a>
                        </div>
                    </div>
                </div>

                @*

            <div class="col mb-4">
                <div class="card">
                    <img src="https://cdn0.iconfinder.com/data/icons/business-and-finance-glyph-24/64/business-and-finance-glyph-24-12-512.png" class="card-img-top" alt="..." />
                    <div class="card-body">
                        <h5 class="card-title">Admin Settings</h5>
                        <p class="card-text">Change settings and controls for admin.</p>
                        <a asp-area="" asp-controller="Home" asp-action="AdminSettings" class="stretched-link"></a>
                    </div>
                </div>
            </div>
            <div class="col mb-4">
                <div class="card">
                    <img src="https://cdn0.iconfinder.com/data/icons/project-management-1-14/65/44-512.png" class="card-img-top" alt="..." />
                    <div class="card-body">
                        <h5 class="card-title">Worker Settings</h5>
                        <p class="card-text">Change setting and controls for workers.</p>
                        <a asp-area="" asp-controller="Home" asp-action="WorkerSettings" class="stretched-link"></a>
                    </div>
                </div>
            </div>



                <div class="col mb-4">
                    <div class="card">
                        <img src="https://cdn3.iconfinder.com/data/icons/business-and-finance-glyph-20/64/business-and-finance-glyph-20-10-512.png" class="card-img-top" alt="..." />
                        <div class="card-body">
                            <h5 class="card-title">User Management</h5>
                            <p class="card-text">Add new users and modify roles</p>
                            <a asp-area="" asp-controller="UserManagement" asp-action="Index" class="stretched-link"></a>
                        </div>
                    </div>
                </div>
            </div>
        </div>
        </div>
    </div>
*@

CloudCemeteryManagementSystem/CloudCemeteryManagementSystem/Views/Home/AdminSettings.cshtml
@{
    ViewData["Title"] = "AdminSettings";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<head>

    <link rel="stylesheet" href="~/css/DashBack.css">

    <style type="text/css">
        body {
            background-image: url('https://www.pixeden.com/media/k2/galleries/93/003-subtle-light-pattern-background-texture.jpg');
            background-size: cover;
            background-attachment: fixed;
        }

        .settings {
            color: black;
        }
    </style>
</head>

<div class="container">
    <div class="text-block">
        <div class="settings">
            <h1>
                <b>Admin Settings</b>
            </h1>
            <hr />

            <h3>Admin Information:</h3>
            <form class="needs-validation" novalidate>
                <div class="form-row">
                    <div class="col-md-4 mb-3">
                        <label for="validationTooltip01">First name</label>
                        <input type="text" class="form-control" id="validationTooltip01" value="Mark" required>
                        <div class="valid-tooltip">
                            Looks good!
                        </div>
                    </div>
                    <div class="col-md-4 mb-3">
                        <label for="validationTooltip02">Last name</label>
                        <input type="text" class="form-control" id="validationTooltip02" value="Otto" required>
                        <div class="valid-tooltip">
                            Looks good!
                        </div>
                    </div>
                </div>
                <div class="form-row">
                    <div class="col-md-6 mb-3">
                        <label for="validationTooltip03">City</label>
                        <input type="text" class="form-control" id="validationTooltip03" required>
                        <div class="invalid-tooltip">
                            Please provide a valid city.
                        </div>
                    </div>
                    <div class="col-md-3 mb-3">
                        <label for="validationTooltip04">State</label>
                        <select class="custom-select" id="validationTooltip04" required>
                            <option selected disabled value="">Choose...</option>
                            <option>...</option>
                        </select>
                        <div class="invalid-tooltip">
                            Please select a valid state.
                        </div>
                    </div>
                    <div class="col-md-3 mb-3">
                        <label for="validationTooltip05">Zip</label>
                        <input type="text" class="form-control" id="validationTooltip05" required>
                        <div class="invalid-tooltip">
                            Please provide a valid zip.
                        </div>
                    </div>
                </div>
                <button class="btn btn-primary" type="submit">Submit</button>
            </form>

            <br />
            <br />


            <h3>Change Password:</h3>
            <form>
                <div class="form-row">
                    <div class="form-group col-md-6">
                        <label for="inputEmail4">Old Password</label>
                        <input type="password" class="form-control" id="inputEmail4">
                    </div>
                    <div class="form-group col-md-6">
                        <label for="inputPassword4">New Password</label>
                        <input type="password" class="form-control" id="inputPassword4">
                    </div>
                </div>
                <button type="submit" class="btn btn-primary">Submit</button>
            </form>
        </div>
    </div>
</div>

CloudCemeteryManagementSystem/CloudCemeteryManagementSystem/Views/Home/ErrorPleaseSignIn.cshtml
@{
    ViewData["Title"] = "ErrorPleaseSignIn";
}
<head>
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <link rel="stylesheet" href="~/css/buttons.css" />

    <style type="text/css">
        body {
            background-image: url(https://www.stratoscale.com/wp-content/uploads/2019/05/bigstock-168398480.jpg);
            background-size: cover;
            background-attachment: fixed;
            margin: 0px;
            padding: 0px;
            font-family: 'Times New Roman';
        }

        .text-block {
            border: 2px solid black;
            border-radius: 25px;
            position: fixed;
            background-color: white;
            color: white;
            padding-top: 40px;
            padding-left: 45px;
            padding-right: 45px;
            padding-bottom: 40px;
            opacity: 0.7;
        }

        .centerd {
            left: 0;
            line-height: 200px;
            margin-top: -100px;
            position: absolute;
            text-align: center;
            top: 50%;
            width: 100%;
        }
    </style>
</head>

<body>
    <div>
        <div class="centerd">
            <h1 class="elegantshadow"><center><font color="black"><b>Login to View </b></font></center></h1>
            <h1 class="elegantshadow"><center><font color="black"><b>Dashboards!</b></font></center></h1>
            <p><center><font color="black"><b>Contact Kim Hunt for more information</b></font></center></p>
        </div>
    </div>
</body>

CloudCemeteryManagementSystem/CloudCemeteryManagementSystem/Views/Home/Index.cshtml
@{
    ViewData["Title"] = "Home Page";
}

<head>

    <meta name="viewport" content="width=device-width, initial-scale=1">
    <link rel="stylesheet" href="~/css/buttons.css" />

    <style type="text/css">
        body {
            background-image: url(https://www.stratoscale.com/wp-content/uploads/2019/05/bigstock-168398480.jpg);
            background-size: cover;
            background-attachment: fixed;
            margin: 0px;
            padding: 0px;
            font-family: 'Times New Roman';
        }

        .text-block {
            position: fixed;
            height: 100%;
            width: 100%;
            border-right: 2px solid white;
            border-left: 2px solid white;
            border-radius: 25px;
            background-color: black;
            color: white;
            padding-top: 40px;
            padding-left: 45px;
            padding-right: 45px;
            padding-bottom: 40px;
            opacity: 0.85;
            top: 50%;
        }

        .centerd {
            left: 0;
            line-height: 200px;
            margin-top: -100px;
            position: absolute;
            text-align: center;
            top: 50%;
            width: 100%;
            z-index: 7000;
        }
    </style>
</head>

<body>
    <div>
        <div class="centerd">
            <h1 class="elegantshadow"><center><font><b>Saints Peter & Paul</b></font></center></h1>
            <h1 class="elegantshadow"><center><font><b>Managment System</b></font></center></h1>
        </div>
    </div>
</body>

CloudCemeteryManagementSystem/CloudCemeteryManagementSystem/Views/Home/SearchInterredInfo.cshtml
@{
    ViewData["Title"] = "SearchInterredInfo";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<style type="text/css">
    body {
        background-image: url('https://www.pixeden.com/media/k2/galleries/93/003-subtle-light-pattern-background-texture.jpg');
        background-size: cover;
        background-attachment: fixed;
    }
</style>

<h2>SearchInterredInfo</h2>

CloudCemeteryManagementSystem/CloudCemeteryManagementSystem/Views/Home/SearchLotOwnerInfo.cshtml
@{
    ViewData["Title"] = "SearchLotOwnerInfo";
    Layout = "~/Views/Shared/_Layout.cshtml";
}
<style type="text/css">
    body {
        background-image: url('https://www.pixeden.com/media/k2/galleries/93/003-subtle-light-pattern-background-texture.jpg');
        background-size: cover;
        background-attachment: fixed;
    }
</style>

<h2>SearchLotOwnerInfo</h2>

CloudCemeteryManagementSystem/CloudCemeteryManagementSystem/Views/Home/WorkerDashboardPlaceHolder.cshtml
@{
    ViewData["Title"] = "WorkerDashboardPlaceHolder";
}

<h1>Welcome to the Worker Dashboard!</h1>

CloudCemeteryManagementSystem/CloudCemeteryManagementSystem/Views/Home/WorkerSettings.cshtml
@{
    ViewData["Title"] = "WorkerSettings";
    Layout = "~/Views/Shared/_Layout.cshtml";
}
<style type="text/css">
    body {
        background-image: url('https://www.pixeden.com/media/k2/galleries/93/003-subtle-light-pattern-background-texture.jpg');
        background-size: cover;
        background-attachment: fixed;
    }
</style>

<h2>WorkerSettings</h2>